# PersistentVolume - O "disco rígido" para o MySQL
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: mysql
    type: local
spec:
  capacity:
    storage: 2Gi                    # 2GB para ambiente de desenvolvimento
  accessModes:
    - ReadWriteOnce               # Apenas 1 Pod pode escrever por vez
  persistentVolumeReclaimPolicy: Retain  # Manter dados mesmo se PVC for deletado
  storageClassName: manual        # Classe de storage manual
  hostPath:
    path: /mnt/mysql-data         # Pasta no node do Minikube
    type: DirectoryOrCreate       # Criar pasta se não existir

---
# PersistentVolumeClaim - "Requisição de espaço" do MySQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce               # Mesmo access mode do PV
  resources:
    requests:
      storage: 2Gi                # Pedir 2GB (mesmo tamanho do PV)
  storageClassName: manual        # Mesmo storageClassName do PV