services:
  # Serviço de Autoatendimento
  autoatendimento:
    build:
      context: ./autoatendimento
      dockerfile: Dockerfile
    container_name: lanchonete-autoatendimento
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=lanchonetedb
      - DB_USERNAME=lanchonete
      - DB_PASSWORD=lanchonete
      - SPRING_SQL_INIT_PLATFORM=mysql
      - SPRING_SQL_INIT_MODE=always
      - SPRING_H2_CONSOLE_ENABLED=false
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - lanchonete-network

  # Serviço de Pagamento (Mock Mercado Pago)
  pagamento:
    build:
      context: ./pagamento
      dockerfile: Dockerfile
    container_name: lanchonete-pagamento
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SPRING_PROFILES_ACTIVE=prod
      - MOCK_WEBHOOK_URL=http://autoatendimento:8080/webhook/pagamento
    depends_on:
      - autoatendimento
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - lanchonete-network

  db:
    image: mysql:8.0
    container_name: lanchonete-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=lanchonetedb
      - MYSQL_USER=lanchonete
      - MYSQL_PASSWORD=lanchonete
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "lanchonete", "-p$$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped
    networks:
      - lanchonete-network

networks:
  lanchonete-network:
    driver: bridge

volumes:
  mysql_data: