# Configurações específicas para o ambiente de produção
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:lanchonetedb}?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
sql:
  init:
    mode: always
    platform: mysql
  h2:
    console:
      enabled: false
  # Configurações de logging
  logging:
    level:
      org.springframework.jdbc.datasource.init: DEBUG
      org.springframework.jdbc.core: TRACE
      br.com.lanchonete.autoatendimento: DEBUG