# Configurações específicas para o ambiente de produção
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:lanchonetedb}?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
      platform: mysql
      schema-locations: classpath:schema-mysql.sql
      data-locations: classpath:data-mysql.sql
  h2:
    console:
      enabled: false

# Configurações de logging
logging:
  level:
    root: WARN
    org.springframework: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.boot: INFO
    org.springframework.jdbc.datasource.init: WARN
    org.springframework.jdbc.core: WARN
    org.hibernate: WARN
    com.mysql: WARN
    com.zaxxer.hikari: WARN
    br.com.lanchonete.autoatendimento: INFO