CREATE TABLE IF NOT EXISTS cliente (
    id IDENTITY PRIMARY KEY,
    cpf VARCHAR(11) NOT NULL,
    nome VARCHAR NOT NULL,
    email VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS produto (
    id IDENTITY PRIMARY KEY,
    nome VARCHAR NOT NULL UNIQUE,
    descricao VARCHAR,
    preco DECIMAL(10,2) NOT NULL,
    categoria VARCHAR NOT NULL
);