apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    app: mysql
    component: config
data:
  # Configurações do banco de dados
  MYSQL_DATABASE: "lanchonete"
  MYSQL_CHARACTER_SET_SERVER: "utf8mb4"
  MYSQL_COLLATION_SERVER: "utf8mb4_unicode_ci"
  
  # Configurações de performance para ambiente limitado
  MYSQL_INNODB_BUFFER_POOL_SIZE: "64M"
  MYSQL_MAX_CONNECTIONS: "100"
  MYSQL_QUERY_CACHE_SIZE: "16M"
  MYSQL_QUERY_CACHE_TYPE: "1"