# Profile Kubernetes com configuração mais explícita
spring:
  # FORÇAR MYSQL - NÃO H2
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql-service}:${DB_PORT:3306}/${DB_NAME:lanchonete}?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:lanchonete}
    password: ${DB_PASSWORD:lanchonete123}

  # DESABILITAR H2 EXPLICITAMENTE
  h2:
    console:
      enabled: false

  # CONFIGURAÇÕES DE INICIALIZAÇÃO
  sql:
    init:
      mode: always
      platform: mysql
      schema-locations: classpath:schema-mysql.sql
      data-locations: classpath:data-mysql.sql
      continue-on-error: true

  # JPA/HIBERNATE PARA MYSQL
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
    defer-datasource-initialization: true

  # Configurações de lifecycle
  lifecycle:
    timeout-per-shutdown-phase: 30s

# Configurações do servidor
server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

# Configurações do Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

# Logging mais detalhado para debug
logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc: DEBUG
    br.com.lanchonete: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"