# Profile Kubernetes com Actuator TOTALMENTE configurado
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql-service}:${DB_PORT:3306}/${DB_NAME:lanchonete}?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:lanchonete}
    password: ${DB_PASSWORD:lanchonete123}

  h2:
    console:
      enabled: false

  sql:
    init:
      mode: always
      platform: mysql
      schema-locations: classpath:schema-mysql.sql
      data-locations: classpath:data-mysql.sql
      continue-on-error: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
    defer-datasource-initialization: true

  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

# CONFIGURAÇÃO COMPLETA DO ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true                     # Habilitar /health/readiness
    livenessstate:
      enabled: true                     # Habilitar /health/liveness
    db:
      enabled: true                     # Health check do banco
    diskspace:
      enabled: true                     # Health check de disco
  server:
    port: ${SERVER_PORT:8080}           # Actuator na mesma porta da app

# Logging
logging:
  level:
    org.springframework.boot.actuate: DEBUG  # Debug do Actuator
    br.com.lanchonete: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"