# Service NodePort para Pagamento
apiVersion: v1
kind: Service
metadata:
  name: pagamento-service
  labels:
    app: pagamento
    component: service
spec:
  type: NodePort                    # Tipo NodePort para acesso externo
  selector:
    app: pagamento                  # Conecta com Pods que têm label app=pagamento
  ports:
    - name: http
      port: 8081                      # Porta interna do Service
      targetPort: 8081                # Porta do container
      nodePort: 30081                 # Porta externa (mesmo que estava funcionando)
      protocol: TCP