# Service NodePort para Pagamento
apiVersion: v1
kind: Service
metadata:
  name: pagamento-service
  labels:
    app: pagamento
    component: service
spec:
  type: LoadBalancer                # Tipo LoadBalancer para acesso externo via ELB
  selector:
    app: pagamento                  # Conecta com Pods que têm label app=pagamento
  ports:
    - name: http
      port: 8081                      # Porta interna do Service
      targetPort: 8081                # Porta do container
      protocol: TCP