apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autoatendimento-hpa
  labels:
    app: autoatendimento
    component: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: autoatendimento-deployment
  minReplicas: 2
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90          # Threshold bem alto
