apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autoatendimento-hpa
  labels:
    app: autoatendimento
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: autoatendimento-deployment
  
  # Configuração de réplicas
  minReplicas: 2                    # Mínimo que já está rodando
  maxReplicas: 4                    # Máximo para minikube (não sobrecarregar)
  
  # Métricas de scaling
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60      # 60% de 100m = 60m CPU target
          # Atual: 8-9m, então precisa 6-7x mais carga

  # Comportamento de scaling (EQUILIBRADO)
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60     # Aguardar 1min antes de escalar up
      policies:
        - type: Replicas
          value: 1                         # Adicionar 1 pod por vez
          periodSeconds: 60                # A cada 1 minuto
        - type: Percent
          value: 50                        # Ou 50% dos pods atuais
          periodSeconds: 60
      selectPolicy: Max                  # Usar a política mais agressiva

    scaleDown:
      stabilizationWindowSeconds: 180    # Aguardar 3min antes de escalar down
      policies:
        - type: Replicas
          value: 1                         # Remover 1 pod por vez
          periodSeconds: 120               # A cada 2 minutos
      selectPolicy: Min                  # Política mais conservadora