apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: autoatendimento-hpa
  labels:
    app: autoatendimento
    component: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: autoatendimento-deployment
  minReplicas: 2                           # Mínimo: sempre 2 Pods
  maxReplicas: 6                           # Máximo: reduzido de 10 para 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70             # MENOS SENSÍVEL: 45% → 70%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80             # Adicionar métrica de memória
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300      # MAIS CONSERVADOR: 20s → 5min
      policies:
        - type: Percent
          value: 50                          # MENOS AGRESSIVO: 150% → 50%
          periodSeconds: 60                  # MAIS LENTO: 20s → 60s
        - type: Pods
          value: 2                           # MENOS PODS: 4 → 2 por vez
          periodSeconds: 60
      selectPolicy: Min                    # CONSERVADOR: Max → Min
    scaleDown:
      stabilizationWindowSeconds: 600      # MAIS CONSERVADOR: 2min → 10min
      policies:
        - type: Percent
          value: 10                          # MUITO CONSERVADOR: 25% → 10%
          periodSeconds: 120                 # MAIS LENTO: 30s → 2min
        - type: Pods
          value: 1                           # Remove apenas 1 pod por vez
          periodSeconds: 120
      selectPolicy: Min                    # Política mais conservadora