apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pagamento-hpa
  labels:
    app: pagamento
    component: hpa
    version: "simples"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pagamento-deployment
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 85