# Profile Kubernetes com Actuator CONFIGURADO COM SEGURANÇA
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql-service}:${DB_PORT:3306}/${DB_NAME:lanchonete}?useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:lanchonete}
    password: ${DB_PASSWORD}  # ✅ SEM VALOR PADRÃO - força uso de Secret

  h2:
    console:
      enabled: false

  sql:
    init:
      mode: embedded  # ✅ SEGURO - só executa se banco embedded
      platform: mysql
      schema-locations: classpath:schema-mysql.sql
      data-locations: classpath:data-mysql.sql
      continue-on-error: true

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
    defer-datasource-initialization: true

  lifecycle:
    timeout-per-shutdown-phase: 30s

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

# CONFIGURAÇÃO SEGURA DO ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,info"  # ✅ APENAS ENDPOINTS ESSENCIAIS
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
    db:
      enabled: true
    diskspace:
      enabled: true
  server:
    port: ${SERVER_PORT:8080}

# CONFIGURAÇÃO DO SWAGGER PARA KUBERNETES
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    display-request-duration: true
    display-operation-id: true

# Logging
logging:
  level:
    br.com.lanchonete: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"