# Configurações do H2 com JDBC
spring:
  datasource:
    url: jdbc:h2:mem:lanchonetedb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      platform: h2
      schema-locations: classpath:schema-h2.sql
      data-locations: classpath:data-h2.sql
jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  defer-datasource-initialization: true

# Servidor
server:
  port:8080

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
