# Deployment do Autoatendimento - STARTUP PROBE IGUAL AO PAGAMENTO
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoatendimento-deployment
  labels:
    app: autoatendimento
spec:
  replicas: 2
  selector:
    matchLabels:
      app: autoatendimento
  template:
    metadata:
      labels:
        app: autoatendimento
    spec:
      containers:
        - name: app
          image: lanchonete-app_autoatendimento:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: http

          # Configurações via ConfigMap e Secret
          envFrom:
            - configMapRef:
                name: autoatendimento-config
            - secretRef:
                name: mysql-secret

          # RESOURCE LIMITS OTIMIZADOS PARA HPA SENSÍVEL
          resources:
            requests:
              memory: "300Mi"
              cpu: "100m"             # REDUZIDO: 150m → 100m (mais sensível)
            limits:
              memory: "600Mi"
              cpu: "400m"

          # STARTUP PROBE IGUAL AO PAGAMENTO
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 15
            successThreshold: 1

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1