apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  labels:
    app: mysql
spec:
  serviceName: mysql-headless-service
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          # OTIMIZAÇÃO 1: MySQL 5.7 (mais leve que 8.0)
          image: mysql:5.7
          ports:
            - containerPort: 3306
              name: mysql

          # Configurações básicas via environment
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
            - name: MYSQL_DATABASE
              value: "lanchonete"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password

          # OTIMIZAÇÃO 2: Configurações ultra-lean para minikube
          args:
            - --innodb-buffer-pool-size=32M        # Reduzido de 128M padrão
            - --innodb-log-file-size=16M          # Reduzido para economizar I/O
            - --innodb-flush-log-at-trx-commit=2  # Menos durabilidade, mais performance
            - --max-connections=50                # Reduzido de 151 padrão
            - --table-open-cache=32              # Reduzido de 2000 padrão
            - --query-cache-size=8M              # Cache pequeno mas útil
            - --query-cache-type=1               # Habilitar query cache
            - --query-cache-limit=1M             # Limite por query
            - --thread-cache-size=4              # Cache de threads pequeno
            - --tmp-table-size=8M                # Tabelas temporárias menores
            - --max-heap-table-size=8M           # Heap tables menores
            - --sort-buffer-size=256K            # Buffer de ordenação menor
            - --read-buffer-size=128K            # Buffer de leitura menor
            - --join-buffer-size=128K            # Buffer de join menor
            - --skip-name-resolve                # Não resolver nomes (mais rápido)
            - --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO

          # Volume mount
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql

          # OTIMIZAÇÃO 3: Resources baseados no consumo real observado
          resources:
            requests:
              memory: "300Mi"     # Baseado nos 409Mi observados
              cpu: "50m"          # Reduzido (observado: 23m)
            limits:
              memory: "400Mi"     # Limite próximo ao request
              cpu: "200m"         # Limite conservador

          # OTIMIZAÇÃO 4: Health checks otimizados (menos agressivos)
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - "mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD"
            initialDelaySeconds: 20      # Reduzido de 30s
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 8          # Reduzido de 10
            successThreshold: 1

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "mysql -h localhost -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
            successThreshold: 1

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD"
            initialDelaySeconds: 60       # Aumentado para dar tempo de estabilizar
            periodSeconds: 15             # Menos frequente
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1

      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc