# Deployment do Pagamento - CONFIGURAÇÃO FINAL SENSÍVEL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pagamento-deployment
  labels:
    app: pagamento
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pagamento
  template:
    metadata:
      labels:
        app: pagamento
    spec:
      containers:
        - name: app
          image: lanchonete-app-pagamento:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
              name: http

          # Configurações via ConfigMap
          envFrom:
            - configMapRef:
                name: pagamento-config

          # RESOURCE LIMITS OTIMIZADOS PARA HPA ULTRA SENSÍVEL
          resources:
            requests:
              memory: "200Mi"
              cpu: "50m"              # REDUZIDO: 100m → 50m (ultra sensível)
            limits:
              memory: "400Mi"
              cpu: "300m"

          # Health checks otimizados (mais tolerantes após ajustes)
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 15
            successThreshold: 1

          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 5
            successThreshold: 1

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 5
            successThreshold: 1