# Profile específico para Kubernetes
server:
  port: ${SERVER_PORT:8081}
  shutdown: graceful

spring:
  application:
    name: pagamento-service
  
  # Configurações de lifecycle para graceful shutdown
  lifecycle:
    timeout-per-shutdown-phase: 30s

# Configuração do mock do Mercado Pago (usando service names do Kubernetes)
mock:
  webhook:
    url: ${MOCK_WEBHOOK_URL:http://autoatendimento-service:8080/webhook/pagamento}
  processamento:
    delay: ${MOCK_DELAY:3000}  # 3 segundos em milissegundos
  aprovacao:
    percentual: ${MOCK_APPROVAL_RATE:80}  # 80% de aprovação

# Configurações do Spring Boot Actuator para health checks
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true  # Habilita endpoints /health/liveness e /health/readiness
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

# Configuração do Swagger (mantém igual ao padrão)
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Configurações de logging
logging:
  level:
    br.com.lanchonete: ${LOG_LEVEL:INFO}
    org.springframework.web: ${LOG_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"