# Profile Kubernetes Pagamento com Actuator TOTALMENTE configurado
server:
  port: ${SERVER_PORT:8081}
  shutdown: graceful

spring:
  application:
    name: pagamento-service
  lifecycle:
    timeout-per-shutdown-phase: 30s

# Configuração do mock
mock:
  webhook:
    url: ${MOCK_WEBHOOK_URL:http://autoatendimento-service:8080/webhook/pagamento}
  processamento:
    delay: ${MOCK_DELAY:3000}
  aprovacao:
    percentual: ${MOCK_APPROVAL_RATE:80}

# CONFIGURAÇÃO COMPLETA DO ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include: "*"                    # Expor TODOS os endpoints
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true                   # CRITICAL: Habilitar probes
  health:
    readinessstate:
      enabled: true                     # Habilitar /health/readiness
    livenessstate:
      enabled: true                     # Habilitar /health/liveness
    diskspace:
      enabled: true                     # Health check de disco
  server:
    port: ${SERVER_PORT:8081}           # Actuator na mesma porta da app

# Configuração do Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Logging
logging:
  level:
    br.com.lanchonete: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"