DROP TABLE IF EXISTS cliente;

CREATE TABLE cliente (
    id IDENTITY PRIMARY KEY,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    nome VARCHAR NOT NULL,
    email VARCHAR NOT NULL
);

DROP TABLE IF EXISTS produto;

CREATE TABLE produto (
    id IDENTITY PRIMARY KEY,
    nome VARCHAR NOT NULL UNIQUE,
    descricao VARCHAR,
    preco DECIMAL(10,2) NOT NULL,
    categoria VARCHAR NOT NULL
);
