# Service normal do MySQL - para aplicações se conectarem
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  type: ClusterIP                 # Acesso apenas interno ao cluster
  selector:
    app: mysql                    # Conecta com Pods que têm label app=mysql
  ports:
  - name: mysql
    port: 3306                    # Porta do Service
    targetPort: 3306              # Porta do container MySQL
    protocol: TCP

---
# Headless Service - necessário para StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless-service
  labels:
    app: mysql
spec:
  clusterIP: None                 # Headless = sem ClusterIP
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP